// ISO 3166-1 alpha-2 → flag emoji (literal strings — no String.fromCodePoint)
const CODE: Record<string, string> = {
  AF:'🇦🇫', AL:'🇦🇱', DZ:'🇩🇿', AD:'🇦🇩', AO:'🇦🇴', AG:'🇦🇬', AR:'🇦🇷', AM:'🇦🇲',
  AU:'🇦🇺', AT:'🇦🇹', AZ:'🇦🇿', BS:'🇧🇸', BH:'🇧🇭', BD:'🇧🇩', BB:'🇧🇧', BY:'🇧🇾',
  BE:'🇧🇪', BZ:'🇧🇿', BJ:'🇧🇯', BT:'🇧🇹', BO:'🇧🇴', BA:'🇧🇦', BW:'🇧🇼', BR:'🇧🇷',
  BN:'🇧🇳', BG:'🇧🇬', BF:'🇧🇫', BI:'🇧🇮', CV:'🇨🇻', KH:'🇰🇭', CM:'🇨🇲', CA:'🇨🇦',
  CF:'🇨🇫', TD:'🇹🇩', CL:'🇨🇱', CN:'🇨🇳', CO:'🇨🇴', KM:'🇰🇲', CG:'🇨🇬', CD:'🇨🇩',
  CR:'🇨🇷', CI:'🇨🇮', HR:'🇭🇷', CU:'🇨🇺', CY:'🇨🇾', CZ:'🇨🇿', DK:'🇩🇰', DJ:'🇩🇯',
  DM:'🇩🇲', DO:'🇩🇴', EC:'🇪🇨', EG:'🇪🇬', SV:'🇸🇻', GQ:'🇬🇶', ER:'🇪🇷', EE:'🇪🇪',
  SZ:'🇸🇿', ET:'🇪🇹', FJ:'🇫🇯', FI:'🇫🇮', FR:'🇫🇷', GA:'🇬🇦', GM:'🇬🇲', GE:'🇬🇪',
  DE:'🇩🇪', GH:'🇬🇭', GR:'🇬🇷', GD:'🇬🇩', GT:'🇬🇹', GN:'🇬🇳', GW:'🇬🇼', GY:'🇬🇾',
  HT:'🇭🇹', HN:'🇭🇳', HU:'🇭🇺', IS:'🇮🇸', IN:'🇮🇳', ID:'🇮🇩', IR:'🇮🇷', IQ:'🇮🇶',
  IE:'🇮🇪', IL:'🇮🇱', IT:'🇮🇹', JM:'🇯🇲', JP:'🇯🇵', JO:'🇯🇴', KZ:'🇰🇿', KE:'🇰🇪',
  KI:'🇰🇮', KP:'🇰🇵', KR:'🇰🇷', KW:'🇰🇼', KG:'🇰🇬', LA:'🇱🇦', LV:'🇱🇻', LB:'🇱🇧',
  LS:'🇱🇸', LR:'🇱🇷', LY:'🇱🇾', LI:'🇱🇮', LT:'🇱🇹', LU:'🇱🇺', MG:'🇲🇬', MW:'🇲🇼',
  MY:'🇲🇾', MV:'🇲🇻', ML:'🇲🇱', MT:'🇲🇹', MH:'🇲🇭', MR:'🇲🇷', MU:'🇲🇺', MX:'🇲🇽',
  FM:'🇫🇲', MD:'🇲🇩', MC:'🇲🇨', MN:'🇲🇳', ME:'🇲🇪', MA:'🇲🇦', MZ:'🇲🇿', MM:'🇲🇲',
  NA:'🇳🇦', NR:'🇳🇷', NP:'🇳🇵', NL:'🇳🇱', NZ:'🇳🇿', NI:'🇳🇮', NE:'🇳🇪', NG:'🇳🇬',
  MK:'🇲🇰', NO:'🇳🇴', OM:'🇴🇲', PK:'🇵🇰', PW:'🇵🇼', PA:'🇵🇦', PG:'🇵🇬', PY:'🇵🇾',
  PE:'🇵🇪', PH:'🇵🇭', PL:'🇵🇱', PT:'🇵🇹', QA:'🇶🇦', RO:'🇷🇴', RU:'🇷🇺', RW:'🇷🇼',
  KN:'🇰🇳', LC:'🇱🇨', VC:'🇻🇨', WS:'🇼🇸', SM:'🇸🇲', ST:'🇸🇹', SA:'🇸🇦', SN:'🇸🇳',
  RS:'🇷🇸', SC:'🇸🇨', SL:'🇸🇱', SG:'🇸🇬', SK:'🇸🇰', SI:'🇸🇮', SB:'🇸🇧', SO:'🇸🇴',
  ZA:'🇿🇦', SS:'🇸🇸', ES:'🇪🇸', LK:'🇱🇰', SD:'🇸🇩', SR:'🇸🇷', SE:'🇸🇪', CH:'🇨🇭',
  SY:'🇸🇾', TW:'🇹🇼', TJ:'🇹🇯', TZ:'🇹🇿', TH:'🇹🇭', TL:'🇹🇱', TG:'🇹🇬', TO:'🇹🇴',
  TT:'🇹🇹', TN:'🇹🇳', TR:'🇹🇷', TM:'🇹🇲', TV:'🇹🇻', UG:'🇺🇬', UA:'🇺🇦', AE:'🇦🇪',
  GB:'🇬🇧', US:'🇺🇸', UY:'🇺🇾', UZ:'🇺🇿', VU:'🇻🇺', VE:'🇻🇪', VN:'🇻🇳', YE:'🇾🇪',
  ZM:'🇿🇲', ZW:'🇿🇼',
}

// Full country name (pt-BR and en) → ISO code
const NAME_TO_CODE: Record<string, string> = {
  'afghanistan':'AF','afeganistão':'AF','albania':'AL','albânia':'AL','algeria':'DZ',
  'argélia':'DZ','andorra':'AD','angola':'AO','antigua and barbuda':'AG','antígua e barbuda':'AG',
  'argentina':'AR','armenia':'AM','armênia':'AM','australia':'AU','austrália':'AU',
  'austria':'AT','áustria':'AT','azerbaijan':'AZ','azerbaijão':'AZ','bahamas':'BS',
  'bahrain':'BH','bahrein':'BH','bangladesh':'BD','barbados':'BB','belarus':'BY',
  'bielorrússia':'BY','belgium':'BE','bélgica':'BE','belize':'BZ','benin':'BJ','benim':'BJ',
  'bhutan':'BT','butão':'BT','bolivia':'BO','bolívia':'BO','bosnia and herzegovina':'BA',
  'bósnia e herzegovina':'BA','botswana':'BW','brazil':'BR','brasil':'BR','brunei':'BN',
  'bulgaria':'BG','bulgária':'BG','burkina faso':'BF','burundi':'BI','cabo verde':'CV',
  'cape verde':'CV','cambodia':'KH','camboja':'KH','cameroon':'CM','camarões':'CM',
  'canada':'CA','canadá':'CA','central african republic':'CF','república centro-africana':'CF',
  'chad':'TD','chade':'TD','chile':'CL','china':'CN','colombia':'CO','colômbia':'CO',
  'comoros':'KM','comores':'KM','congo':'CG','democratic republic of the congo':'CD',
  'república democrática do congo':'CD','costa rica':'CR','croatia':'HR','croácia':'HR',
  'cuba':'CU','cyprus':'CY','chipre':'CY','czech republic':'CZ','czechia':'CZ',
  'república tcheca':'CZ','república checa':'CZ','denmark':'DK','dinamarca':'DK',
  'djibouti':'DJ','djibuti':'DJ','dominica':'DM','dominican republic':'DO',
  'república dominicana':'DO','ecuador':'EC','equador':'EC','egypt':'EG','egito':'EG',
  'el salvador':'SV','equatorial guinea':'GQ','guiné equatorial':'GQ','eritrea':'ER',
  'eritreia':'ER','estonia':'EE','estônia':'EE','eswatini':'SZ','suazilândia':'SZ',
  'ethiopia':'ET','etiópia':'ET','fiji':'FJ','finland':'FI','finlândia':'FI',
  'france':'FR','frança':'FR','gabon':'GA','gabão':'GA','gambia':'GM','gâmbia':'GM',
  'georgia':'GE','geórgia':'GE','germany':'DE','alemanha':'DE','ghana':'GH','greece':'GR',
  'grécia':'GR','grenada':'GD','granada':'GD','guatemala':'GT','guinea':'GN','guiné':'GN',
  'guinea-bissau':'GW','guiné-bissau':'GW','guyana':'GY','guiana':'GY','haiti':'HT',
  'haití':'HT','honduras':'HN','hungary':'HU','hungria':'HU','iceland':'IS','islândia':'IS',
  'india':'IN','índia':'IN','indonesia':'ID','indonésia':'ID','iran':'IR','irã':'IR',
  'iraq':'IQ','iraque':'IQ','ireland':'IE','irlanda':'IE','israel':'IL','italy':'IT',
  'itália':'IT','jamaica':'JM','japan':'JP','japão':'JP','jordan':'JO','jordânia':'JO',
  'kazakhstan':'KZ','cazaquistão':'KZ','kenya':'KE','quênia':'KE','kiribati':'KI',
  'north korea':'KP','coreia do norte':'KP','south korea':'KR','coreia do sul':'KR',
  'kuwait':'KW','kyrgyzstan':'KG','quirguistão':'KG','laos':'LA','latvia':'LV',
  'letônia':'LV','lebanon':'LB','líbano':'LB','lesotho':'LS','liberia':'LR','libéria':'LR',
  'libya':'LY','líbia':'LY','liechtenstein':'LI','lithuania':'LT','lituânia':'LT',
  'luxembourg':'LU','luxemburgo':'LU','madagascar':'MG','malawi':'MW','malaysia':'MY',
  'malásia':'MY','maldives':'MV','maldivas':'MV','mali':'ML','malta':'MT',
  'marshall islands':'MH','ilhas marshall':'MH','mauritania':'MR','mauritânia':'MR',
  'mauritius':'MU','maurício':'MU','mexico':'MX','méxico':'MX','micronesia':'FM',
  'micronésia':'FM','moldova':'MD','monaco':'MC','mônaco':'MC','mongolia':'MN',
  'mongólia':'MN','montenegro':'ME','morocco':'MA','marrocos':'MA','mozambique':'MZ',
  'moçambique':'MZ','myanmar':'MM','birmânia':'MM','namibia':'NA','namíbia':'NA',
  'nauru':'NR','nepal':'NP','netherlands':'NL','países baixos':'NL','holanda':'NL',
  'new zealand':'NZ','nova zelândia':'NZ','nicaragua':'NI','nicarágua':'NI','niger':'NE',
  'nigeria':'NG','nigéria':'NG','north macedonia':'MK','macedônia do norte':'MK',
  'norway':'NO','noruega':'NO','oman':'OM','omã':'OM','pakistan':'PK','paquistão':'PK',
  'palau':'PW','panama':'PA','panamá':'PA','papua new guinea':'PG','papua-nova guiné':'PG',
  'paraguay':'PY','paraguai':'PY','peru':'PE','philippines':'PH','filipinas':'PH',
  'poland':'PL','polônia':'PL','portugal':'PT','qatar':'QA','romania':'RO','romênia':'RO',
  'russia':'RU','rússia':'RU','rwanda':'RW','saint kitts and nevis':'KN',
  'são cristóvão e névis':'KN','saint lucia':'LC','santa lúcia':'LC',
  'saint vincent and the grenadines':'VC','são vicente e granadinas':'VC','samoa':'WS',
  'san marino':'SM','são tomé and príncipe':'ST','são tomé e príncipe':'ST',
  'saudi arabia':'SA','arábia saudita':'SA','senegal':'SN','serbia':'RS','sérvia':'RS',
  'seychelles':'SC','sierra leone':'SL','singapore':'SG','singapura':'SG','slovakia':'SK',
  'eslováquia':'SK','slovenia':'SI','eslovênia':'SI','solomon islands':'SB',
  'ilhas salomão':'SB','somalia':'SO','somália':'SO','south africa':'ZA','áfrica do sul':'ZA',
  'south sudan':'SS','sudão do sul':'SS','spain':'ES','espanha':'ES','sri lanka':'LK',
  'sudan':'SD','sudão':'SD','suriname':'SR','sweden':'SE','suécia':'SE',
  'switzerland':'CH','suíça':'CH','syria':'SY','síria':'SY','taiwan':'TW',
  'tajikistan':'TJ','tajiquistão':'TJ','tanzania':'TZ','tanzânia':'TZ','thailand':'TH',
  'tailândia':'TH','timor-leste':'TL','timor leste':'TL','togo':'TG','tonga':'TO',
  'trinidad and tobago':'TT','trindade e tobago':'TT','tunisia':'TN','tunísia':'TN',
  'turkey':'TR','turquia':'TR','türkiye':'TR','turkmenistan':'TM','turcomenistão':'TM',
  'tuvalu':'TV','uganda':'UG','ukraine':'UA','ucrânia':'UA',
  'united arab emirates':'AE','emirados árabes unidos':'AE','united kingdom':'GB',
  'reino unido':'GB','united states':'US','estados unidos':'US',
  'united states of america':'US','uruguay':'UY','uruguai':'UY','uzbekistan':'UZ',
  'uzbequistão':'UZ','vanuatu':'VU','venezuela':'VE','vietnam':'VN','vietnã':'VN',
  'viet nam':'VN','yemen':'YE','iêmen':'YE','zambia':'ZM','zâmbia':'ZM',
  'zimbabwe':'ZW','zimbábue':'ZW',
}

/** Full name or 2-letter ISO → ISO code (uppercase), or null if unknown */
export function toIsoCode(name: string): string | null {
  const t = name.trim()
  if (t.length === 2 && /^[A-Za-z]{2}$/.test(t)) return t.toUpperCase()
  return NAME_TO_CODE[t.toLowerCase()] ?? null
}

/** Full name or 2-letter ISO → flag emoji */
export function countryFlag(name: string): string {
  const code = toIsoCode(name)
  return code ? (CODE[code] ?? name) : name
}
